from snakemake.utils import min_version

min_version("6.4.1")

workdir: "results/" + config['experiment_id']

include: "rules/download.smk"
include: "rules/sequencing.smk"
include: "rules/slap_polya.smk"
include: "rules/genemodels.smk"

# One rule to rule them all...
rule all:
    input:
        "splice_polyA.gff",